### ISSUE TITLE
Uint1Array is not a constructor  

### ISSUE THREAD

**Issue by nottledim** [crislin2046/Uint1Array#7]
I can't get it to work even using your example.  I've tried using node v12.13 and v14.7
It says:
`
const bits = new Uint1Array(buf);
             ^
TypeError: Uint1Array is not a constructor
`

`const Uint1Array = require('uint1array');
const message = "JAVASCRIPT ROCKS";
const chars = message.split('').map( c => c.charCodeAt(0) );

const buf = new ArrayBuffer(chars.length);
const bytes = new Uint8Array(buf);
const bits = new Uint1Array(buf);

bytes.set(chars);

console.log(`${bits}`); `

**Comment by crisdosaygo** [comment]
Sorry there was a typo. When using CommonJS modules you need to require `.default`

I've updated the example in the README to reflect.

Thank you very much for your report.
